Repository registreerocks/rtc-data, pull requests merged in 2021-05, with the labels that each got.

#44 feat(cors): add cors config options
  Cargo.lock
  rtc_data_service/http_server/Cargo.toml
  rtc_data_service/http_server/config/default.toml
  rtc_data_service/http_server/src/main.rs
  rtc_data_service/src/app_config.rs
Labels: enhancement

#45 refactor(rtc_data_service,http_server): simpler TLS config
  rtc_data_service/http_server/config/default.toml
  rtc_data_service/http_server/config/production.toml
  rtc_data_service/http_server/src/main.rs
  rtc_data_service/src/app_config.rs
Labels: data_service, maintenance

#46 build(rtc_data_enclave): fix file target typo
  rtc_data_enclave/Makefile
Labels: bug, data_enclave

#47 refactor(enclave): move shared code to tenclave
  Cargo.lock
  Cargo.toml
  rtc_data_enclave/Cargo.lock
  rtc_data_enclave/Cargo.toml
  rtc_data_enclave/src/data_upload.rs
  rtc_data_enclave/src/lib.rs
  rtc_tenclave/Cargo.lock
  rtc_tenclave/Cargo.toml
  rtc_tenclave/rust-toolchain
  rtc_tenclave/src/crypto.rs
  rtc_tenclave/src/lib.rs
  rtc_tenclave/src/util.rs
Labels: maintenance

#52 build(docker): ignore all nested Cargo target directories
  .dockerignore
Labels: maintenance

#58 build: fix some more Makefile build / rebuild issues
  rtc_auth_enclave/Makefile
  rtc_data_enclave/Makefile
Labels: auth_enclave, bug, data_enclave, maintenance

#53 Update encrypt/decrypt API to add and remove padding (similar to C++ API for nacl)
  codegen/auth_enclave/bindings.h
  codegen/data_enclave/bindings.h
  rtc_data_service/tests/data_upload.rs
  rtc_tenclave/src/crypto.rs
  rtc_types/src/data_upload.rs
Labels: bug

#55 Add remote attestation support for the Authorization Enclave
  codegen/data_enclave/bindings.h
  rtc_auth_enclave/Cargo.lock
  rtc_auth_enclave/Cargo.toml
  rtc_auth_enclave/build.rs
  rtc_auth_enclave/src/lib.rs
  rtc_data_enclave/Cargo.lock
  rtc_data_enclave/build.rs
  rtc_data_enclave/src/lib.rs
  rtc_tenclave/Cargo.lock
  rtc_tenclave/Cargo.toml
  rtc_tenclave/src/enclave.rs
  rtc_tenclave/src/lib.rs
Labels: auth_enclave, enhancement

#61 feat: trusted key-value store using sgxfs
  rtc_auth_enclave/Cargo.lock
  rtc_data_enclave/Cargo.lock
  rtc_data_enclave/Cargo.toml
  rtc_tenclave/Cargo.lock
  rtc_tenclave/Cargo.toml
  rtc_tenclave/src/kv_store/fs/inspect.rs
  rtc_tenclave/src/kv_store/fs/mod.rs
  rtc_tenclave/src/kv_store/fs/sgx_filer.rs
  rtc_tenclave/src/kv_store/fs/std_filer.rs
  rtc_tenclave/src/kv_store/in_memory.rs
  rtc_tenclave/src/kv_store/inspect.rs
  rtc_tenclave/src/kv_store/mod.rs
  rtc_tenclave/src/kv_store/tests.rs
  rtc_tenclave/src/lib.rs
Labels: enhancement

#78 chore: update rust version for enclave crates
  rtc_auth_enclave/Cargo.lock
  rtc_auth_enclave/Cargo.toml
  rtc_auth_enclave/rust-toolchain
  rtc_data_enclave/Cargo.lock
  rtc_data_enclave/Cargo.toml
  rtc_data_enclave/rust-toolchain
  rtc_tenclave/Cargo.lock
  rtc_tenclave/Cargo.toml
  rtc_tenclave/rust-toolchain
  rtc_types/src/lib.rs
Labels: maintenance

#80 Clean up SGX dependencies and patches
  Cargo.lock
  Cargo.toml
  HACKING.md
  rtc_auth_enclave/Cargo.lock
  rtc_auth_enclave/Cargo.toml
  rtc_data_enclave/Cargo.lock
  rtc_data_enclave/Cargo.toml
  rtc_data_service/Cargo.toml
  rtc_tenclave/Cargo.lock
  rtc_tenclave/Cargo.toml
  rtc_types/Cargo.toml
  rtc_uenclave/Cargo.toml
  rtc_uenclave/auth-sys/Cargo.toml
  rtc_uenclave/data-ocalls/Cargo.toml
  rtc_uenclave/data-sys/Cargo.toml
  rtc_uenclave/rtc-ecalls/Cargo.toml
Labels: maintenance

#60 Add local attestation support
  Cargo.lock
  Cargo.toml
  HACKING.md
  buildenv.mk
  codegen/auth_enclave/bindings.h
  codegen/auth_enclave/rtc_auth_t.c
  codegen/auth_enclave/rtc_auth_t.h
  codegen/auth_enclave/rtc_auth_u.c
  codegen/auth_enclave/rtc_auth_u.h
  codegen/data_enclave/bindings.h
  codegen/data_enclave/rtc_data_t.c
  codegen/data_enclave/rtc_data_t.h
  codegen/data_enclave/rtc_data_u.c
  codegen/data_enclave/rtc_data_u.h
  edl/rtc_tenclave.edl
  rtc_auth_enclave/Cargo.lock
  rtc_auth_enclave/Makefile
  rtc_auth_enclave/rtc_auth.edl
  rtc_auth_enclave/src/lib.rs
  rtc_data_enclave/Cargo.lock
  rtc_data_enclave/Makefile
  rtc_data_enclave/rtc_data.edl
  rtc_data_enclave/src/lib.rs
  rtc_data_service/tests/exec_token.rs
  rtc_tenclave/Cargo.lock
  rtc_tenclave/Cargo.toml
  rtc_tenclave/src/dh/mod.rs
  rtc_tenclave/src/dh/protected_channel.rs
  rtc_tenclave/src/dh/sessions.rs
  rtc_tenclave/src/dh/types.rs
  rtc_tenclave/src/lib.rs
  rtc_types/src/dh.rs
  rtc_types/src/lib.rs
  rtc_udh/Cargo.toml
  rtc_udh/src/lib.rs
  rtc_udh/src/responder.rs
  rtc_uenclave/Cargo.toml
  rtc_uenclave/auth-sys/Cargo.toml
  rtc_uenclave/auth-sys/build.rs
  rtc_uenclave/auth-sys/src/lib.rs
  rtc_uenclave/auth-sys/wrapper.h
  rtc_uenclave/data-sys/Cargo.toml
  rtc_uenclave/data-sys/build.rs
  rtc_uenclave/data-sys/src/lib.rs
  rtc_uenclave/data-sys/wrapper.h
  rtc_uenclave/src/ecalls.rs
  rtc_uenclave/src/enclaves/rtc_auth.rs
  rtc_uenclave/src/enclaves/rtc_data.rs
  rtc_uenclave/src/rtc_enclave.rs
Labels: auth_enclave, data_enclave, enhancement
